name: compile_docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        use-mamba: true

    - name: Initialize conda
      shell: bash -l {0}
      run: conda init bash

    - name: Activate conda environment, install dependencies 
      shell: bash -l {0}
      run: |
        source ~/.bashrc
        conda env create -f Dev_tools/swiftpol.yml
        conda activate swiftpol
        conda install sphinx sphinx_rtd_theme 
        pip install -e .

    - name: Run build
      shell: bash -l {0}
      run: |
        source ~/.bashrc
        conda activate swiftpol
        sphinx-build -b html docs/ docs/_build/   

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.DOCS }}
        publish_dir: ./docs/_build/html 